name: Deploy Storybook to GH Pages

on:
  push:
    branches: [main]         # run every push to main
  workflow_dispatch:         # manual trigger

permissions:
  contents: write             # needed for gh‑pages commit
  pages: write                # only if you use actions/deploy-pages
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'        # or 'pnpm'/'yarn'

      - name: Install deps
        run: npm ci           # or pnpm install --frozen-lockfile

      - name: Build Storybook
        run: npm run build-storybook

      # ─── Deploy to GitHub Pages ─────────────────────────────────────────
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './storybook-static'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
